version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    environment:
      - ASPNETCORE_ENVIRONMENT: Heroku
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Unit tests
          command: dotnet test TheExampleApp.Tests
      - run:
          name: Integration tests
          command: dotnet test TheExampleApp.IntegrationTests