version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Unit tests
          command: dotnet test TheExampleApp.Tests
      - run:
          name: Integration tests
          command: dotnet test TheExampleApp.IntegrationTests
      - run:
          name: Publish app
          command: dotnet publish theexampleapp -o /app
      - run:
          name: Switch directory
          command: cd /app
      - run:
          name: Run app
          command: dotnet run
          background: true
      - run: Switch directory back
        name: cd ..
      - run:
          name: Run E2E tests
          command: dotnet test TheExampleApp.E2eTests