version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Unit tests
          command: dotnet test TheExampleApp.Tests
      - run:
          name: Integration tests
          command: dotnet test TheExampleApp.IntegrationTests
      - run:
          name: Run app
          command: dotnet run  TheExampleApp &
      - run:
          name: Clone e2e tests
          command: git clone https://github.com/contentful/the-example-app-e2e-tests.git ./test/e2e