version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Unit tests
          command: dotnet test TheExampleApp.Tests
      - run:
          name: Integration tests
          command: dotnet test TheExampleApp.IntegrationTests
      - run:
          name: Run app
          command: cd TheExampleApp ; dotnet run &
      - run:
          name: Run E2E tests
          command: cd TheExampleApp.E2eTests ; dotnet test