version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Unit tests
          command: dotnet test TheExampleApp.Tests
      - run:
          name: Integration tests
          command: dotnet test TheExampleApp.IntegrationTests
      - run:
          name: Run app
          command: cd TheExampleApp ; dotnet run &
      - run:
          name: Install latest version of ChromeDriver Sample
          command: |
            sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get install google-chrome-unstable
      - run:
          name: Run E2E tests
          command: cd TheExampleApp.E2eTests ; chmod a+x chromedriver ; dotnet test